### ISSUE TITLE
Link naar werkende demo ontbreekt

### ISSUE THREAD

**Issue by KrijnHoetmer** [heleensnoeck/browser_technologie#1]
Waar kunnen we de boel zien? :)

**Comment by heleensnoeck** [comment]
Hee krijn ik ben net een tijdje bezig geweest om hem online te zetten via github pages... maar hij is met node gebouwd dus dit wil niet lukken... 

http://stackoverflow.com/questions/15718649/how-to-publish-a-website-made-by-node-js-to-github-pages

nieuwe code is nu wel gepushed naar git

**Comment by KrijnHoetmer** [comment]
Gaat dit ondertussen wel al lukken? Misschien via die andere host, die meer studenten gebruiken?
