### ISSUE TITLE
HTML bevat een paar bugjes/is wat rommelig

### ISSUE THREAD

**Issue by KrijnHoetmer** [heleensnoeck/browser_technologie#2]
Haal je HTML bijvoorbeeld eens door https://html5.validator.nu/ heen.

Paar dingen die me opvallen (en die een validator niet gaat zien):
- Een `<h4>` in je `<nav>`; waarom?
- Waar linkt `<a href="#closeNavNow">` heen?
- Wat doen `<div class="nav-ul">` en `<span class="nav-li">`?
- Inline event handlers (zoals `ondrop` en `onsubmit`); niet fout, maar kan netter. Hoe?
- `<div class="title title-done">`; heb je die wrappers echt nodig?

**Comment by heleensnoeck** [comment]
Punt 1: luiheid (opgelost)

punt 2: Dat was omdat ik het menu in wilde laten klappen met een target (is weg)

punt 3: Nav li zorgt voor de achtergrond en houd de li op zijn plaats de li zijn de punten die er met een before opgezet zijn. Ik vind het netjes je zou een li ul kunnen doen.

punt 4: Je zou hem volledig in javascript op kunnen bouwen dus function ondrop.. 

Punt 5: Nee, had ik niet toch vind ik het wel prettiger om te scheiden(zeker als je een grote site maakt met veel h1), maar ik heb het aangepast op de h1. 
h1 {
    font-size: 1.2em;
    font-family: Arial, sans-serif;
    text-transform: uppercase;
    left: 6em;
    position: relative;
    width: 100%;
    height: 2em;
    top: 1em;
    position: relative;
}

**Comment by KrijnHoetmer** [comment]
Kun je je nieuwe code ook pushen naar GitHub?
