### ISSUE TITLE
JS bevat geen feature detection

### ISSUE THREAD

**Issue by KrijnHoetmer** [heleensnoeck/browser_technologie#3]
Kijk bijvoorbeeld naar de Cutting the Mustard techniek om dit af te vangen. Je gaat er nu bijvoorbeeld van uit dat `querySelector`, `XMLHttpRequest` en `addEventListener` altijd aanwezig zijn, wat niet per se een handige aanname is. Test vooral ook in oudere IE browsers om te kijken wat er gebeurt.

**Comment by heleensnoeck** [comment]
Ik heb het volgende toegepast:  
bron: https://learn-the-web.algonquindesign.ca/topics/progressive-enhancement/  

var cutsTheMustard = ('querySelector' in document && 'localStorage' in window && 'addEventListener' in window)
            var js; 

```
        if(cutsTheMustard) {
            js = document.createElement('script');
            js.src = '/javascripts/script.js';
            js.async = true; 
            document.querySelector('script').parentNode.appendChild(js);
        }
```

**Comment by KrijnHoetmer** [comment]
Hm, maar `localStorage` gebruik je niet, `XMLHttpRequest` wel. Pas op met standaard code kopiëren, en probeer het concept erachter te begrijpen.

**Comment by heleensnoeck** [comment]
Ik heb hier een video voor gekeken en ook nog op zijn website verdere tips gelezen dit heb ik alleen over het hoofd gezien... 
var cutsTheMustard = ('querySelector' in window && 'addEventListener' in window)
